### ISSUE TITLE
Auto reconnect to Rooms

### ISSUE THREAD

**Issue by HumanG33k** [profanity-im/profanity#1009]
hello,
Maybe i miss something.

When i start profanity (Version 0.5.1 on debian testing) it auto connect to room like i want.
When the server i use to auth myself (not the same where room is hosted) reboot there is no reconnection  and the autojoin message is on.

Is it a bug ? If not maybe it’s good idea to have an auto reconnect feature in this case.

**Comment by varac** [comment]
Same issue for me - also happens when I switch my VPN or reconnect to my wifi.

**Comment by varac** [comment]
Is this related to #832

**Comment by varac** [comment]
So my current "workaround" is to always close the rooms and rejoin again :/

**Comment by HumanG33k** [comment]
Yes, but it’s not really fun to do it twice by day.

**Comment by varac** [comment]
Yeah, it's the most annoying bug in profanity for me at the moment (profanity is still great, don't get me wrong!).

**Comment by pasis** [comment]
I checked code and it seems that Profanity has functionality of joining all rooms with autojoin flag on reconnect. But it doesn't rejoin other opened rooms. I'm not sure if "autojoin" rooms rejoin automatically (because there can be a bug, I haven't tested it) and what happens if username is in use due to the ghost session.

So, this feature needs to be implemented.

**Comment by HumanG33k** [comment]
It’s also can come from the server. I have to do more test (when/if i have the time). It’s look like on some server the reconnection occurs.

**Comment by jubalh** [comment]
Fixed in da54eaf42b88be62bfebbb84dd11cb9bdd4cd9bd
