### ISSUE TITLE
OMEMO: Autocomplete suggests fingerprints not belonging to the selected contact

### ISSUE THREAD

**Issue by philipflohr** [profanity-im/profanity#1068]
The OMEMO autocomplete feature suggests fingerprints not belonging to the selected contact.

Steps to reproduce:
1. Enable omemo (set policy to automatic / always - not tested if this is needed to reproduce...)
2. Show the fingerprint list of one of your contacts
3. Write `/omemo trust <contact>` and use tab for autocompletion
-> Many fingerprints are suggested, not only the ones belonging to the contact

**Comment by jubalh** [comment]
Yes so far it's all the fingerprints we get.

**Comment by paulfariello** [comment]
AFAICT we don't have access to the first argument of a command from the autocompletion command.
So I can't filter out fingerprints easily.
@pasis, @boothj5  can you confirm?

**Comment by jubalh** [comment]
If we don't solve this (ever or for 0.7.0) then we should document the usage at https://profanity-im.github.io/omemo.html

Maybe also mentioning that people should enable carbons (or auto enabling them for 0.7.0 since I think that most people want them and only some prefer to disable them). And describing that they need to trust their own keys of other devices.

Mentioning that file transfer is not encrypted since its another XEP too.

So that they know how to use OMEMO properly with Profanity and what works and what doesn'.

**Comment by jubalh** [comment]
I documented this on the website now. We will release 0.7.0 as it is and hope users read the documentation.

Planning to tackle this for 0.8.0.

**Comment by jubalh** [comment]
> AFAICT we don't have access to the first argument of a command from the autocompletion command.
So I can't filter out fingerprints easily.

@paulfariello  We could create a new function. Autocomplete still has it in the `input` argument.

**Comment by paulfariello** [comment]
We should merge all omemo autocomplete functions into a single one in order to filter the fingerprints.
