### ISSUE TITLE
Feature request: display and switch to more than ten active windows

### ISSUE THREAD

**Issue by kaffeekanne** [profanity-im/profanity#1114]
As of now profanity only allows to jump to 10 active windows via `alt-#` and `/win #`. All above are adressed by ther title `/win <windowtitle/number>`.

Like in irssi it woult be convenient to have the line qwert(yz)uiop line of keys adress windows 11 to 20.

Edit: jumping to high numbers works already, so "just" mapping to further shortcuts would be missing.

**Comment by ccxcz** [comment]
There are several ways I'm used to navigate channels in my IRC client. The probably most frequent / useful is alt-a (both Irssi and Weechat) which jumps to next active window. I tend to order my windows based on priority they have to me so I have it set to jump to lowest numbered window with unread message, with highlights taking priority.
The other one that is quite handy is Weechat's alt+j+number for double digits. <https://www.weechat.org/files/doc/stable/weechat_user.en.html#key_bindings_buffers_windows> This allows for fairly quick jumping without having to erase typed text on the command line and also avoids embarrassing /win messages sent to people as there is no need to press the enter key. This of course needs the ability to handle multi-key sequences, but since alt is already expressed as character sequence in almost every terminal (exception being glass terminals from 70s before 8-bit character sets became the norm) this shouldn't be a problem.
The third and most complex one is the go.py plugin for Weechat <https://weechat.org/blog/post/2009/02/08/Script-go> which allows you to use fuzzy search among the buffer names (akin to dmenu, anything.el, zaw, fzf and lot of other similar applications/plugins) which is useful when one has really a lot of buffers open.
One more thing to consider is how to display which channels are active. Currently Profanity has list of open windows (called tabs in /help statusbar?) but IRC clients usually instead have hotlist there: just the windows with unread messages / activity. If we want to support having a lot of windows open I think having option to show only those with certain level of activity in the statusbar would be rather practical.

**Comment by jubalh** [comment]
Documenting current findings:

irssi hardcoded the alt + 1234567890qwertyuio into their code: https://github.com/irssi/irssi/blob/master/src/fe-text/gui-readline.c#L1144
They have a `BIND` command which lets users write plugins like this: https://github.com/irssi/scripts.irssi.org/blob/master/scripts/keybinds.pl

We also have 0-9 hardcoded: https://github.com/profanity-im/profanity/blob/master/src/ui/inputwin.c#L374
We could easily add the qwertyuio there.

**Comment by jubalh** [comment]
With https://github.com/profanity-im/profanity/commit/d6c638c70fd6fe7170ac144fe858b93bdfd2eacb we support  alt + 1234567890qwertyuio now.

**Comment by jubalh** [comment]
> The probably most frequent / useful is alt-a (both Irssi and Weechat) which jumps to next active window.

Active means a window with unread messages?

**Comment by jubalh** [comment]
https://github.com/profanity-im/profanity/commit/e8420e7235c4a9217f32ef98984e7b6ee5a11cdf makes alt-a switch to the next window with unread messages.

**Comment by jubalh** [comment]
There have some nice ideas been mentioned in here.
However I won't implement them. PRs might get accepted.

I'll close this issue since the feature requested from @kaffeekanne is completed. And additionally `alt-a` has been added.
