### ISSUE TITLE
On reconnect MUCs don't all get rejoined properly

### ISSUE THREAD

**Issue by ccxcz** [profanity-im/profanity#1120]
Following up from #1083. Upon reconnect some MUC windows stop getting new messages and aren't able to send messages either. They are listed as connected in `/bookmark list` and `/join` doesn't seem to have any effect besides jumping to that window. This is on 172436a83f5cae500ce73d7cb00d0cfbd4a84c8d (current HEAD).

**Comment by jubalh** [comment]
My guess is that they didnt really reconnect. I need to check why, but it was hard to reproduce.
`/join` probably checks if a window is already open that is associated with the muc (and not if connected) and then just jumps to it. Maybe this needs to be improved.

**Comment by jubalh** [comment]
https://github.com/profanity-im/profanity/blob/master/src/event/server_events.c#L91 here we rejoin password protected MUCs upon.
It means we send a presence stanza to that MUC in that case. I'm not sure why only in that case.

**Comment by jubalh** [comment]
I tested this again. And on my private server all MUCs get rejoined. They are public and not password protected. However profanity@rooms.dismail.de does not get rejoined.

**Comment by jubalh** [comment]
Turns out there are different ways to joins a MUC.
XEP-0045 was adapted at one point. And profanity still uses the old method of just sending a presence update.
My test server uses prosody 0.10.2. Thus for me it works on those channel.

In prosody 0.11.x support for the old method was removed, and this is probably what dismail uses.

So we need to implement https://xmpp.org/extensions/xep-0045.html#enter for this to work.

Thanks to Zash and MattJ‎ for the help.

**Comment by jubalh** [comment]
#1127 should fix this issue.
But since we rely on old MUC join we get:
`Tue 06:21:00 AM - Error from profanity@rooms.dismail.de/nick: You must join the room before sending presence updates` for newer prosody servers.
