### ISSUE TITLE
Make /info a bit more user friendly

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1194]
If you use `/info contact` while you're in a chat window with "contact" profanity doesn't show the info but only tells you that it's not necessary to specify the contact.

## Expected Behavior
Show you the info anyway but additionally inform that it's not necessary to specify the contact.

## Current Behavior
Profanity doesn't show the info but only tells you that it's not necessary to specify the contact.

## Steps to Reproduce (for bugs)
1. /msg contact
2. /info contact
3. Profanity shows only `No parameter required when in chat`
4. /info
5. The info is shown

## Environment
Debian Testing

```
profanity --version
Profanity, version 0.7.0dev.master.fd161d92
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (2.7.16+)
GTK icons: Enabled
```

**Comment by mdosch** [comment]
The behavior for `/status` is the same.

**Comment by jubalh** [comment]
I'm not sure what's the best expected behaviour.
It could be that the user types `/info someotheruser` which is not the one he has in the active chat window.
So I think the correct behaviour would be: use the second parameter always if specified. If not use the nick of the active window when in a chat. And never notify about additional parameter. The only thing is that the output will then only be in console window.

**Comment by mdosch** [comment]
I guess that would be a good solution.
