### ISSUE TITLE
Add /roster toggle functionality (PR provided)

### ISSUE THREAD

**Issue by quite** [profanity-im/profanity#1250]
It would be nice with a toggle functionaliy, to manage all those roster show/hide interactively.

This also adds the previous value of the preference to the console output on show/hide/toggle.

**Comment by jubalh** [comment]
Thanks for your PR!
I didn't read the code yet nor try it. But how does the toggle differ from the show/hide?
I think the functionality is actually the same and the user sees if he has a roster or not. So he can type `show` in case he has one.
So why introduce a new command for the same functionality? :)

**Comment by quite** [comment]
I should have added that if adds toggle to all of the different items that can be shown and hidden. Such as `/toggle roster offline`.

Yes, especially the roster if self (`/toggle roster`) can be seen if it is shown, and it is clear if it is missing. The point of toggle is especially for those items that you can't see. For example `/roster toggle offline` -- you will not see the state of it, if there are no contacts offline. `/roster toggle offline` will then toggle the pref (and also display the previous pref). In some situations this feels very useful, at least for me. Sometimes it does indeed feel superfluous.

**Comment by jubalh** [comment]
The reason for toggle still doesn't convince me. I don't see much of a point in it to be honest :)

But I like a lot the general cleanup you did to that code. It's much less lines and more readable now!
Also I would like to encourage you to contribute more ;)

So I'm personally against adding a new `toggle` command since it's too similar to hide/show. Especially we we have the string `"was enabled"` now.

In https://github.com/profanity-im/profanity/issues/1116 we tried to get rid of duplicate/similar commands. Like `/leave` and `/close`.

But I'm totally for your PR with just the cleanup code!

However I'm also willing to merge it as it is. So just let me know: do you really want the toggle command? Then I'll merge. If you on second thought think it's not necessary then I would appreciate if you could change your PR so we get the cleanup anyways :)

**Comment by quite** [comment]
I hear you. I'm no longer convinced myself about the `/toggle`. I'll factor it out, and bring it back if I become convinced later. And yes, showing previous value does help.
