### ISSUE TITLE
Don't see messages from other clients in log when profanity starts

### ISSUE THREAD

**Issue by amacfie** [profanity-im/profanity#1405]
Apologies if this is a silly issue.

When profanity is running, I see messages sent by my account using another client as long as the carbons setting is on. When profanity starts, I see messages from other accounts that were sent when profanity was closed. But I don't see messages sent by my account using another client when profanity was closed. Is there a way to enable this? If not, I request the feature.

I use an Android client and if I send messages using profanity while that client is closed, I see them there when I later open it.

## Expected Behavior
If I send a message with another client when profanity isn't running, I should see it in the log the next time I open profanity.

## Current Behavior
If I send a message with another client when profanity isn't running, I don't see any trace of it in profanity ever.

## Context

Naturally, I like to see the full conversation history from whichever client I use.

## Environment
glib -v:
```
Profanity, version 0.8.1
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2020 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.8.2)
GTK icons: Enabled
```

**Comment by jubalh** [comment]
Not entirely sure I understood you. But:

> When profanity starts, I see messages from other accounts that were sent when profanity was closed. But I don't see messages sent by my account using another client when profanity was closed. 

Account a@b.c is online only with Profanity -> Profanity gets the messages.
Account a@b.c is online with Profanity and Conversations  -> Profanity gets the messages if Carbons are enabled
Account a@b.c is online only with Conversations -> Conversations gets the messages. Profanity will not because they are not sent to it once it connects since they are marked as received by the server.
Account a@b.c is is offline with all clients then goes online with Profanity -> Profanity will receive messages send while we were online because the server didnt mark them as read, they are still in "offline store".

For Profanity to display all past sent messages, no matter whether read or not we need [XEP-0313: Message Archive Management](https://xmpp.org/extensions/xep-0313.html).
Which we track here: https://github.com/profanity-im/profanity/issues/660

And are actively working on. Basic support was merged with PR #1306. But is not enabled yet for the users since its not finished.

**Comment by amacfie** [comment]
Thank you. Similarly, if my account is offline for all clients and I receive a message, if I read the message later on Xabber and then I open Profanity it does not appear in Profanity. Does #660 cover this case too?

**Comment by jubalh** [comment]
Yes, thats the same. Xabber will connect, the messages will be "read" and the server wont have them in offline storage anymore. So once you connect with profanity they are no "new" messages and we don't get them.

**Comment by amacfie** [comment]
Thanks again. BountySource seems to have [problems](https://news.ycombinator.com/item?id=23551098). Is there an alternative method I could use to sponsor the issue?

**Comment by jubalh** [comment]
Oh wow! I wasn't aware of this.
Thanks for sharing, need to check this in more detail later.

So far there are the following ways https://github.com/profanity-im/profanity#donations
If you have more ideas or questions, let me know.

I worked a bit on that feature yesterday btw. I also want it in Profanity. But for the next release 0.10.0 we will focus on cleanup (which will also help us a lot to actually implement the feature).
Depending on how all works out we might still get it for 0.10.0 or the release after. I hope :)

**Comment by jubalh** [comment]
One way might be to use GitHub Sponsors, and sponsor 1 Euro per month. GitHub will double the amount you sponsor there (until Jan 2021). Then once the feature is implemented and you don't want to sponsor any longer you could stop. Or similar.. :)
