### ISSUE TITLE
Feature request: close mucs but remain participant

### ISSUE THREAD

**Issue by huhndev** [profanity-im/profanity#1477]
It would be great if it could be distinguished between '/close' and e.g. '/exit' or '/leave' in mucs, so that you can remove mucs from open tabs, but still be a participant of it.

In my mind, '/exit' or '/leave' would look like the current implementation of '/close' and the new '/close' would just close the tab of the muc. Closed (but not exited) mucs would still be displayed in tab(1) under "Rooms".

With '/join ...' you would reopen both a closed and an exited muc.

**Comment by kaffeekanne** [comment]
Being in a lot of MUCs, i'd appreciate that feature too. My suggestion would be to seperate roster and bookmarks. The tradeoff would be, that in `console` the joined rooms would not be displayed in roster anymore. Mybe `/bookmarks (show|hide)` could be implemented so one could _either_ show roster or bookmarks in `console`. 

As mentioned in #1412 that is probably no easy task and needs quite some overhaul, but joining a lot of mucs to keep track of some discussions without high priorities is a thing and you lose quite some valuable space on `statuswindow` or spend time swapping your windows.

When mentions arrive that muc could be placed as active window in the statusbar. Maybe also when new messages arrive, could be configurable, profanity is a full feature client after all 😉.

**Comment by kaffeekanne** [comment]
That maybe is the thing, highlights should throw a notice, so open a window and highlight that. New messages maybe too (interesting in low noise MUCs), but configurable. I thought i covered that additional requirement in the last paragraph.

I guess it is not a trivial feature request. The overall advantage is to be able to use shortcut keys `Alt -<1....0|q...p>` instead of typing `/win ...` and, for me most important,  not cluttering up the statuswindow.

To be honest, i lowered my MUC count. But i bet this is the only feature holding @weiss back from using profanity as daily driver :-)

**Comment by jubalh** [comment]
I see. In this case this doesn't make any sense to me at all.

> The overall advantage is to be able to use shortcut keys Alt -<1....0|q...p> instead of typing /win ... and, for me most important, not cluttering up the statuswindow.

Doesn't sound like an improvement that is worth implementing.

We have `/statusbar hide read` which will hide the read windows from the statusbar. That should do fine for people who are in many MUCs and feel overwhelmed by the silent ones.

Alt-a and `/win name<tab>` should be good enough for the navigation part.
