### ISSUE TITLE
[Feature request] Support for multiple accounts

### ISSUE THREAD

**Issue by Hund** [profanity-im/profanity#1592]
It would be really neat with support for multiple accounts. Using two instances of the client is not fun at all.

Me personally is a long time use of XMPP and I have two accounts; one for "Hund" and one for the real me. It's where I have my family and friends. I don't consider merging the accounts to be an option, it just wouldn't feel right to be talking to my mom as "Hund". :)

Anyway. Thank you for the work and effort you put into this client! It's nice to see that there's at least someone who cares about a modern console based client for XMPP these days.

**Comment by jubalh** [comment]
1) When you created this issue there was a template that was asking you to not create new feature requests until we re down to 50 issues.
2) https://profanity-im.github.io/faq.html#multiacc
3) https://profanity-im.github.io/blog/post/how-to-run-profanity-instances-within-tmux/

I would recomment to use tmux and run profanity with `profanity -a account1 -t theme1` and `profanity -a account2 -t theme2` so that you visually can also distinguish the two instances better.

**Comment by Hund** [comment]
>     1. When you created this issue there was a template that was asking you to not create new feature requests until we re down to 50 issues.

I know. It showed me 2 open issues though. I guess I didn't clear the search filter before looking.

>     2. https://profanity-im.github.io/faq.html#multiacc
>     3. https://profanity-im.github.io/blog/post/how-to-run-profanity-instances-within-tmux/
> 
> I would recomment to use tmux and run profanity with `profanity -a account1 -t theme1` and `profanity -a account2 -t theme2` so that you visually can also distinguish the two instances better.

It's really not a solution, it's more of an ugly workaround. I appreciate the suggestion though.

You closing the issue means that it's not something that we'll ever see in Profanity?

**Comment by jubalh** [comment]
> You closing the issue means that it's not something that we'll ever see in Profanity?

Not in the near future.
The design of Profanity was always to be one-account only. This is the case since before I started the project. It would be a lot of work to change this. I can see some benefit in doing it at some point. The whole user interface would need a change since each command would need an `-a account` flag so you know for which account you configure something. That's quite ugly in my opinion. Otherwise if you set `/away i'm not here` will be for both accounts that are online. And currently I'm more interested in getting MAM support ready, refactoring the UI so that we have an easier time inserting/updating messages etc.

Personally I prefer the tmux solution mentioned above which gives me even less incentive to work on this multi account support too.

The main reason for closing is like mentioned in above comments: currently we don't accept new feature requests until we are down to 50 open issues. In the meantime people might try to contribute by fixing some issues so that we get down to that number :)

**Comment by Hund** [comment]
I see. Thank you for you comment! :)
