### ISSUE TITLE
Feature request: /quote command with autocomplete

### ISSUE THREAD

**Issue by MarcoPolo-PasTonMolo** [profanity-im/profanity#1599]
Have a /quote command with autocomplete that allows you to quote a message and respond to it.
Copy and pasting isn't that ergonomic especially if the message wraps and you end up copying names of occupants.

This command should probably open the editor because you would probably enter a newline after the quoted text to reply

**Comment by jubalh** [comment]
This is something that we often have thought about ourselves.
The problem is that we want to rewrite the UI first.

There needs to be a way to identify which messages to quote. So we need to change the UI to add some indicator like (1,2,3) in front of the lines or something similar. I didn't really come up with an idea how to identify which message to reply to.

Anyways it seems you didn't read the issue template properly. We are not looking for new feature requests right now until we are down to 50 issues. So users need to help us with that before asking for new features.
