### ISSUE TITLE
Crash due to message recieved before layout->subwin/rosterwin is initialized with NetBSD curses

### ISSUE THREAD

**Issue by alarixnia** [profanity-im/profanity#1769]
Forwarding a bug reported using the NetBSD bug tracker ("Profanity crashes at login"): http://gnats.netbsd.org/57050

The code in question here handles messages by people not in the user's contact list, and what is probably happening is that the XMPP server is sending such a message before profanity has set up its window layout.

Setting `roster.unsubscribed=false` indeed makes profanity start without crashing, and the attached patch bails out early in the  problematic code path if layout->subwin is NULL (Adrian verified for me that either of the two makes profanity work for him again).  But I am not familiar enough with the profanity code to say if this has any issues.

Profanity compiled with ncurses doesn't crash because ncurses's wattron() has a guard against the user passing null pointers, but the X/Open curses library standard doesn't have this guarantee and there's no guard in the NetBSD curses implementation.

```

 --- src/ui/rosterwin.c.orig	2022-05-29 16:45:24.000000000 +0200
 +++ src/ui/rosterwin.c	2022-10-11 13:45:23.394512000 +0200
 @@ -98,10 +98,12 @@
      ProfLayoutSplit* layout = (ProfLayoutSplit*)console->layout;
      assert(layout->memcheck == LAYOUT_SPLIT_MEMCHECK);

 -    if (layout->subwin != NULL) {
 -        werase(layout->subwin);
 +    if (layout->subwin == NULL) {
 +        return;
      }

 +    werase(layout->subwin);
 +
      char* roomspos = prefs_get_string(PREF_ROSTER_ROOMS_POS);
      if (prefs_get_boolean(PREF_ROSTER_ROOMS) && (g_strcmp0(roomspos, "first") == 0)) {
          _rosterwin_print_rooms(layout);
```

**Comment by jubalh** [comment]
I see that the guard that is currently in place was also contributed by you: https://github.com/profanity-im/profanity/commit/ce6775342

So if I see this right, then the bail out makes sure that the other rosterwin functions are not called (like `_rosterwin_print_rooms` etc).

> The code in question here handles messages by people not in the user's contact list, and what is probably happening is that the XMPP server is sending such a message before profanity has set up its window layout.

Does your patch have a side effect (that you are aware of) like the message/window isn't displayed at all? Or will it appear anyways because of the next iteration of this code?

I'll have to check if there is a way to first built the window layout and then react on such events. Need to read the code what we are doing so far..and how..

**Comment by jubalh** [comment]
I was not sure whether the actual issue is somewhere else and this patch would just mask it.
However now a long time passed and I couldnt prove my point or find a fix. So I think the best solution is to take the patch.

@alarixnia do you want to create a PR or should I make a commit?
