### ISSUE TITLE
Simplify adding contacts to roster and subscribing

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#188]
Implement command in profanity to simplify adding contacts and subscriptions e.g:

/sub addbuddy jid [nick]

/sub addbuddy bob.smith@jabber.org bob
- adds them to your roster, with optional nick
- sends a sub request
- accepts their request when it is received

**Comment by kaffeekanne** [comment]
`/sub request <jid>` already adds the buddy to the roster. It does not correctly send a request and does not allow setting a nick. Of course might want to ad some one to the roaster without requesting/allowing presence subscription, like a bookmark for buddies instead of MUCs.

Maybe one can even ditch the subcommans `addbuddy` here, since allow and request are the seperate commanda, but we want some general automation here. What about

`/sub <jid> [nick]`

To automatically add the buddy to the roster, perform at least a request to him and ideally automatically allow an incoming received request?

**Comment by DebXWoody** [comment]
Maybe a settings property flag: "Always accept incoming subscription requests, when the JID is in the roster".

**Comment by jubalh** [comment]
I think current way is good :)
