### ISSUE TITLE
Save all received messages to DB even if duplicate ID is used

### ISSUE THREAD

**Issue by jubalh** [profanity-im/profanity#1899]
This is to track a discussion that we had in the MUC and via PM.

Most of the things were already mentioned in
* https://github.com/profanity-im/profanity/pull/1893#issuecomment-1752434740
* https://github.com/profanity-im/profanity/pull/1893#issuecomment-1755831972

So I believe what needs to be done is:
* Save all messages even with duplicate IDs in DB (don't require <message id=""> to be unique)
* If the server generated stanza-id from XEP-0359: Unique and Stable Stanza IDs is not unique then we use log_warn and print it to console
* With things like Last Message Correction we just use the newest/latest message with that ID

It still would be valuable to find out what other clients do in this case and write it here on the issue.

Issue will most likely be worked on by @H3rnand3zzz  (only can assign you after commented on this thread).

**Comment by jubalh** [comment]
Detailed report :)

It might be that one of us is misunderstanding something.

I don't see the value of `replaces_db_id`.
When we get an LMC message from the server it contains the ID that it should replace. It does *not* contain your self created `replaces_db_id`. So I don't see how you want to associate the LMC message with the correct previously received message. Basically the problem will stay the same. Because you will have several messages in the database with the same  ID. And some of them will have an internal `replaces_db_id`. But then you still don't know WHICH of those to replace because the sender couldn't inform you about that.

Even *if* that would work then you wouldn't need replaces_db_id to have an unique idientifier you could just use the DB ID field, right?

The abstract of XEP-0308 sais: `This specification defines a method for indicating that a message is a correction of the last sent message.`.

So what I believe is the correct behaviour is to replace the *newest* message with the *specified ID* as mentioned in https://github.com/profanity-im/profanity/pull/1893#issuecomment-1755831972 a week ago :)

And as mentioned above (and in the 1893 PR) it would be interesting to check what Dino, Conversations, Gajim are doing. My guess is that they will do exactly that.

**Comment by H3rnand3zzz** [comment]
> I don't see the value of `replaces_db_id`. When we get an LMC message from the server it contains the ID that it should replace. It does _not_ contain your self created `replaces_db_id`. So I don't see how you want to associate the LMC message with the correct previously received message. Basically the problem will stay the same. Because you will have several messages in the database with the same ID. And some of them will have an internal `replaces_db_id`. But then you still don't know WHICH of those to replace because the sender couldn't inform you about that.

The server should find the last record with that particular stanza-id and user in the DB, in the absence of which replacement considered incorrect (no message to replace) -- that's the association part. "Because you will have several messages in the database with the same ID", that would be different, because if I to correct the second part again, it would correct the second part only and vice versa, as we choose only the last correction message.
| ID | stanza_id | replace_id | replaces_db_id | message       |
|----|----------|------------|----------------|---------------|
| 0  | aa       | NULL       | NULL           | Hlo           |
| 1  | xx       | aa         | 0              | Hello         |
| 2  | aa       | NULL       | NULL           | Hw re you     |
| 3  | yy       | aa         | 2              | How are you  |
| 4  | zz       | aa         | 2              | How are you?  |
1st replacement: Hlo -> Hello
2nd replacement: "Hw re you" -> "How are you?" (since we use only the latest replacement with the same DB ID)
Result is unachievable with purse usage of the replace_id


> Even _if_ that would work then you wouldn't need replaces_db_id to have an unique idientifier you could just use the DB ID field, right?

It does not work in the aforementioned case since we can't track which change affects which message.

> The abstract of XEP-0308 sais: `This specification defines a method for indicating that a message is a correction of the last sent message.`.
> 
> So what I believe is the correct behaviour is to replace the _newest_ message with the _specified ID_ as mentioned in [#1893 (comment)](https://github.com/profanity-im/profanity/pull/1893#issuecomment-1755831972) a week ago :)

The problem with that would be that old messages are going to stay uncorrected and also that correction might apply to a new messages (though today I get an idea of workaround for preventing replacement of new messages by checking that replacement message's db id > db id of original)

> And as mentioned above (and in the 1893 PR) it would be interesting to check what Dino, Conversations, Gajim are doing. My guess is that they will do exactly that.
Ok, I can check them and add it do my report, though I guess that no one has a little sophisticated, but powerful system that was proposed.

**Comment by H3rnand3zzz** [comment]
# Additional overview (with code examples) of the potential solutions
## Requirements for the solution
1. Solution MUST be performant. The current implementation searches an unindexed column in the query, causing excessive load. Conditions in SELECT and JOIN clauses MUST use indexed columns or be avoided altogether.
2. `stanza_id` MUST NOT be trusted as an unique identifier.
3. All correction MUST be applied in the order that they were introduced or not applied at all and instead displayed as a plain messages (in accordance with the XEP).
4. In case of subsequent edits, solution MUST adhere to the standard 
> If the same message is to be corrected several times, the id of the original message is used in each case (e.g. If a message of id 1 is corrected by a message of id 2, a subsequent correction should correct 1, not 2).
5. All correction messages SHOULD be saved.


## `replace_db_id` concept
As we can have many messages with the same stanza ID sent at different times, we can have correction messages to them applied at different times as well. There is barely any good way to track the changes accordingly with just the `stanza_id` and `replace_id` columns, since none of them are unique.
| ID | stanza_id | replace_id | message       |
|----|----------|------------|---------------|
| 0  | aa       | NULL       | Hlo           |
| 1  | xx       | aa         | Hello         |
| 2  | aa       | NULL       | Hw re you     |
| 3  | yy       | aa         | How are you   |
| 4  | zz       | aa         | How are you?  |

In this example if rely only upon those 2 we can either replace both messages, replace the last message with the last edit (though it's going to be hard to even make this SQL query not to mention performance of it will violate the first condition).

If we additionally would use ID for this purpose, we can potentially track some bounds in which correction can be applied (but we should priorly find all the "neighbouring" stanzas (rows with the same stanza_id) and then set them as boundaries).

What I offer is to add an additional column `replaces_db_id` which would track to which exact message's (by DB ID) the change should be applied.
| ID | stanza_id | replace_id | replaces_db_id | message       |
|----|----------|------------|----------------|---------------|
| 0  | aa       | NULL       | NULL           | Hlo           |
| 1  | xx       | aa         | 0              | Hello         |
| 2  | aa       | NULL       | NULL           | Hw re you     |
| 3  | yy       | aa         | 2              | How are you   |
| 4  | zz       | aa         | 2              | How are you?  |

On insert we already do the following:
```c
    if (message->replace_id) {
        auto_sqlite char* replace_check_query = sqlite3_mprintf("SELECT `from_jid` FROM `ChatLogs` WHERE `stanza_id` = '%q'",
                                                                message->replace_id ? message->replace_id : "");
```
to ensure integrity of the message's sender.

But what we can do instead is this:
```c
    if (message->replace_id) {
        auto_sqlite char* original_message_query = sqlite3_mprintf("SELECT `id` FROM `ChatLogs` WHERE `stanza_id` = '%q' AND `from_jid` = '%q' AND `replace_db_id` = NULL ORDER BY `id` DESC",
                                                                message->replace_id ? message->replace_id : "",
                                                                from_jid->barejid ? from_jid->barejid : "");
```
This way we can always find the original message and at the same time check integrity of the message's sender.
I offer to do a mental exercise and go one by one in the example table above so you can see how the ID of the exactly previous (at the point of insertion) "original" message is selected (don't forget the condition in C before the query). You can skip the `from_jid` condition as it's out of scope of the problem and is needed only for integrity check. As you can see, it will be kept exactly at the appropriate message at the time.

Visualization for the selection would be about the same, but we would use instead of `replace_id`, `replace_db_id`. Dixi.

## Gajim's way
Gajim offers us a different view and approach on the problem. It's much more performant that other solutions and rely on different mechanisms.

It replaces the message in the DB, but leaves original message in the `additional_data` column stored in JSON, hence it's possible to restore the original message, though it would require us to lose correction metadata (time, stanza_id) or include it in the JSON, which can grow to the questionable sizes, especially in the case of big messages (though it's not often the case). Anyway, on the most important part (data visualization) it's the most performant solution as it does not require any JOINs. The solution for me looks the most appealing due to its performance.

**Comment by H3rnand3zzz** [comment]
> Off topic: The third correction's replace-id will be the second correction's message-id, not the first message-id.
> ID 	stanza_id 	replace_id 	replaces_db_id 	message
> 2 	aa 	NULL 	NULL 	Hw re you
> 3 	yy 	aa 	2 	How are you
> 4 	zz 	**aa** <-- should be **yy** 	2 	How are you?

`If the same message is to be corrected several times, the id of the original message is used in each case (e.g. If a message of id 1 is corrected by a message of id 2, a subsequent correction should correct 1, not 2).` According to [XEP](https://xmpp.org/extensions/xep-0308.html#rules).

> On topic: You shouldn't need **replace_db_id**. You can select the right message by querying for the most recent message-id and sender-jid match.
> 
> Reasoning: Querying for sender-jid will solve the case where there are two messages with the same message-id sent from **different jids**. As for the case where there are two messages with the same message-id sent from the **same jid**, replace the most recent one.

The problem arises from the fact that some senders send non-unique stanza-ids, which was described at the PR and here as well. The sender's integrity check is already present. 

Replacing the most recent one represents a challenge as well, since we need to find which one is the most recent one and for older ones, we should show them "as is", hence the SQL query gets less performant, not to mention that it will be less than perfect solution, especially in case if correction was important (e.g. there was a typo in IBAN), as we can't (and don't have to) enforce users not to use corrections for important changes and in the end it would violate corrected message storage integrity.

**Comment by jubalh** [comment]
@Ppjet6 do you remember what approach you are taking?

**Comment by H3rnand3zzz** [comment]
> > If the same message is to be corrected several times, the id of the original message is used in each case (e.g. If a message of id 1 is corrected by a message of id 2, a subsequent correction should correct 1, not 2).
> 
> Ah! So:
> 
> ```
> <message to='juliet@capulet.net/balcony' id='bad1'>
>   <body>Helo</body>
> </message>
> ```
> 
> We display the message and save it to DB.
> 
> ```
> <message to='juliet@capulet.net/balcony' id='good1'>
>   <body>Hell</body>
>   <replace id='bad1' xmlns='urn:xmpp:message-correct:0'/>
> </message>
> ```
> 
> We save the message to DB. We look for the message with the id `bad1` in the UI and replace it.
> 
> ```
> <message to='juliet@capulet.net/balcony' id='good2'>
>   <body>Hello!</body>
>   <replace id='bad1' xmlns='urn:xmpp:message-correct:0'/>
> </message>
> ```
> 
> We save the message to DB. We look for message with id `bad1` and can't find it because it got replaced by our first correction which has the ID `good1`.
> 
> So _that's_ why you want to save `replaces_db_id`. To always save the ID of the original ID that we want to replace! Why didn't you say so ;)
> 
> So that would mean that we need a new field in the db and in the `ProfMessage` struct?
> 
> Will need to think a bit more about it and and consider Gajim solution. Did you also check other clients btw?

It's rather to keep the message history coherent. We don't touch the original message, but the original message is different at different point in time. It's hard to calculate it dynamically. E.g. today I write to you my IBAN (stanza-id=aa) "122345", I make a mistake there, so I replace it with "12345", tomorrow I write you "Hell" (stanza-id=aa), I fix it with "Hello". But when we are visualizing data, how do we know that we should replace 122345 with "12345" and not "Hello" and that we should replace "Hell" with "Hello" and not "12345" if the message ID is the same? Especially it's problematic when we have multiple edits over the stanza that we meet multiple times. And I've shown that all the originals are getting replace either by last replacement or first replacement, which is wrong. Each message should have its own replacement, but to do that in SQL we either have to calculate every time which replacement applying to which message (it would require additional selects and let's directly forget about it) or use something reliable and unique to know which exact message should be replaced with what. Also we will use replacement dynamically and internally, to initially assign the replacement, we check the latest "original" message (yesterday - IBAN, today - Hell, tomorrow - anything else or maybe still Hell).

But let's focus on the Gajim approach as I like it the most (due to performance gain). In the next few hours I am going to explain their approach, why is it good and how can we implement it (a few ways).

**Comment by H3rnand3zzz** [comment]
Lol, we forgot to close it @jubalh
