### ISSUE TITLE
Unable to connect to selfhosted prosody server

### ISSUE THREAD

**Issue by CalmTechie** [profanity-im/profanity#1960]
- fresh profanity 0.14.0 installation (binary from voidlinux xbps repository)
- /connect _username_@_domain_
- **Login failed**

Debug logs:
https://dormant.observer/-W5N6VNrwES

**Suspicious part:** tried using older version of profanity: 0.13.* (other machine, also precompiled public repository binary)  , and connection was successful
https://dormant.observer/-RWA8TmMPrR

But after package update to 0.14 login fails on this machine as well

## Environment
* profanity -v
https://dormant.observer/-USWNWiV6bw

* Operating System/Distribution
GNU/Linux, VoidLinux distro

* glib version
2.78.0

**Comment by sjaeckel** [comment]
Which version of libstrophe are you using?

0.13.0 has an issue with the SCRAM-PLUS variants which was fixed in https://github.com/strophe/libstrophe/commit/40f2452fb060dcb0a91eeb73671ef2453e31568f

Can you please check and if possible update to 0.13.1?

If you're already on 0.13.1 that's something new and I would kindly ask you to open an issue in the libstrophe repo.
