### ISSUE TITLE
Per window input history

### ISSUE THREAD

**Issue by ledti** [profanity-im/profanity#228]
I've noticed that input history (`Up`) is global rather than window/buffer specific. A general design improvement would be to make it window specific, in my opinion.

A modifier key for global input history should also be considered. As an example, [Weechat](http://www.weechat.org/) uses `Up` for per window input history and `Ctrl+Up` for global input history which seems sane.

**Comment by jubalh** [comment]
Currently we use the history feature of readline.
To my knowledge it only allows to store one history list and not several.

We would need to implement this from scratch.
irssi does what we want https://github.com/irssi/irssi/blob/master/src/fe-text/gui-readline.c#L474

Getting a history object of the current window `history = command_history_current(active_win);` and adding it later `command_history_add(history, str);`.

We can add a check whether we want global history or window history.

I personally like a global history, since sometimes I want to send the same to multiple channels. Or realize I'm in the wrong channel/window just before sending.

**Comment by jubalh** [comment]
Will leave this as is.
