### ISSUE TITLE
Plugins: branch does not compile with Ruby 1.9

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#306]

**Comment by kaffeekanne** [comment]
@jubalh As only python and c plugins are supported now, this could be closed i guess.

**Comment by jubalh** [comment]
Actually this issue is about the `plugins` branch. In which one can [find](https://github.com/profanity-im/profanity/tree/plugins/src/plugins) the start of supporting Ruby and Lua plugins.
This was before my time so I don't know how far it got and why it was never merged into master.

Since I don't know any Ruby and don't plan to support it (yet) you are right: let's close it :-)
