### ISSUE TITLE
OTR HTML Encoding

### ISSUE THREAD

**Issue by NoSkills** [profanity-im/profanity#364]
Pidgin and other IM Clients with OTR capability have a feature called "Convert HTML", which basically removes HTML tags out of the incoming messages.

The problem is that if you communicate with Profanity and OTR to a Pidgin client, HTML is bloating the text and it's very difficult to read.

This is especially true if you're talking to someone using Adium (https://trac.adium.im/ticket/6901) as you will get spammed with < FONT >.

An example copy-paste on something with URL and quotes.
23:24:58 - M: & quot;inspired by hrf=" http://irssi.org/ " >Irssi</ a >& quot;

Anything with a long URL is a complete mess.

**Comment by g-eorge** [comment]
It would be great to have this feature for normal messages too. I have to talk to people on Hipchat and there are often messages created by bots that contain lots of HTML.

**Comment by nd2s** [comment]
I'm also getting these incredible annoying HTML tags everywhere.

I'm unfamiliar with the protocol and I'm not really a C programmer, but I wonder: can't we just convert the whole message content (no matter if OTR or not) into a DOM-like representation and then fetch all the "text-content" parts, insert `\n`s where needed and use the `href`-content of `<a>`s? Or maybe by using XPath? Or isn't the message valid HTML?

**Comment by boothj5** [comment]
The XMPP protocol specifies sending text, not HTML.  There is an extension for [sending XHTML](http://xmpp.org/extensions/xep-0071.html). but this doesn't use the \<body\> element, and so cannot be used to solve this issue.

OTR allows optionally sending HTML, but OTR is used by many chat protocols, in this case where it is used by XMPP, it makes no sense to send HTML.

The same issue has been [reported with Conversations](https://github.com/siacs/Conversations/issues/1166). Chat clients/servers that send HTML and expect the other end to parse it are assuming the other end is not complaint with the protocol, but Profanity is compliant.

The other important comment is how do we know if the sender actually want's to send you HTML and not have it parsed? i.e. someone sends 'Use \<a href="somepage.html"\>A page\</a\> to add a link', we don't want to parse this.

Rather than change the core codebase to be non standards compliant, an option now might be a [plugin](https://github.com/boothj5/profanity-plugins) that allows the user to enable parsing of HTML if they wish, maybe even for specific rooms/contacts.

**Comment by nd2s** [comment]
I did a quick `printf` debug earlier and discovered that the HTML I sent with Gajim was not escaped. This is a total mess.

I agree, this cannot be implemented into the core. The best solution would be to find the responsible Adium developers and punch them. The Adium issue is 9 (!) years old and there seems to be no progress.

Even if this is implemented as a plugin, it can't just remove all HTML tags it finds. Do Profanity plugins have access to contact information while they are processing incoming messages? It would be possible to just check what client the contact users and it could automatically apply the relevant cleaning rules. Like remove all tags and HTML-unescape for Adium clients.
I assume Adium escapes the users' input. I can't test now, I don't have access to Apple systems.

**Comment by boothj5** [comment]
Whilst the senders client information is not passed to plugin when a message is received, the plugins themselves are able to use service discovery to find out this information. The plugin would need to:

1. Listen for presence notifications: ```prof_on_presence_stanza_receive(stanza)```.
2. When a contact or room member appears online, send a [software version request](https://xmpp.org/extensions/xep-0092.html): ```prof.send_stanza(stanza)```.
3. Listen for responses to these requests ```prof_on_iq_stanza_receive(stanza)```.
4. Store the users software version as plugin state. a dictionary for example.
5. When a new chat/room message is received the plugin can check the dictionary for the software being used by the sender and manipulate the message as needed: ```prof_pre_chat_message_display(jid, message)```.

The [clients.py](https://github.com/boothj5/profanity-plugins/blob/master/clients.py) plugin uses software version requests to list client software for everyone in a chat room, so might be a useful reference as a starting point.

I think the plugin should maybe have options to:

* Parse HTML in all messages
* Parse HTML only from specified contacts/rooms
* Parse HTML only from specified client software

This would handle issues with other clients, and chat service XMPP gateways like Hipchat where HTML is common.

**Comment by NiklausHofer** [comment]
Hei guys

I've written a fix for the problem - not for all the points discussed in this thread, but at least for the original bug (Strip HTML from OTR messages). Please check it out and leave your feedback:

  https://github.com/NiklausHofer/profanity/tree/htmlstripper

This is a very simple solution using Regex search and replace to solve the problem. Here is what it does:

- replace all br tags with a newline
- replace all remaining HTML Tags with an empty string
- replace the HTML escaped char &&amp; &&gt; &&lt; with their respective characters & > <

 The option is called "otr striphtml". It's disabled by default. To turn it on, type `/otr striphtml on`.

Using such a simple solution with Regex has both advantages and disadvantages (duh). Here are some points in favour of it:

- Little new code
    - only very little new code has been added to the project
    - No dependencies on large external libraries have been added
    - Only very little additional attack surface has been added
- Fast
    - Regex are fast. Certainly faster than building a DOM

Use your own imagination to find some nice disadvantages ;)

I tested the patch against a current version of gajim, but it should work for Pidgin just as well. Currently abroad on holidays, so no proper internet and no XMPP development environment. Sorry.

Note: The striphtml function I've written could easily be applied to all messages (rather than just OTR messages). It would probably make sense to have both options? But then they need to be aware of each other. That is to say: if HTML stripping for all messages is enabled, then HTML stripping for OTR messages can't be enabled too, since stripping twice could yield weird results. 

Disclaimer: This is my first time working on Profanity. Also I don't do C coding very often. Please go easy on me

**Comment by nd2s** [comment]
Does this decode escaped HTML characters? And does this just remove **all** HTML? Because if so it is unusable as it would replace normal HTML content someone is sending. I'm also not sure if regex will work reliably - but I haven't tested your solution yet (obviously, you just announced it a few moments ago).

I created a sanitise function in python that parses DOM and extracts relevant content but am struggling to get it working as a plugin. I will upload it in a few days, maybe someone can help. Unfortunately I also encountered several other bugs and problems with profanity that are problematic. Need to address them as well.

**Comment by asdil12** [comment]
I didn't look at the patch but using a regex to handle HTML is never a good idea:
http://stackoverflow.com/a/1732454/1234176

**Comment by boothj5** [comment]
@NiklausHofer firstly thanks for your effort in attempting to fix this,

However, as mentioned previously in this thread, the issue is with other clients sending HTML and expecting the receiver to parse it.  The clients sending the HTML are making two assumptions that are incorrect:

1) The receiver will parse HTML.
2) The person sending the message always wants the HTML they send to be parsed.

The XMPP standard defines the message body as text, not HTML, so any standards complaint clients should not parse incoming messages as HTML.

I am not too keen on adding code to Profanity to fix incorrect behaviour other clients, especially when we never know the intention of the sender (do they want it to be parsed or not?).

For that reason, I think a plugin is the best option, whilst the plugin itself will still have the same problem of not knowing senders intention, it seems better to me to have the workaround/hack in a plugin rather than the core codebase.

So apologies for not wanting to add your code at this point, I know that can be frustrating.

**Comment by boothj5** [comment]
@nd2s is there anything I can do to help with the problems you're having?

**Comment by NiklausHofer** [comment]
@nd2s 

> Does this decode escaped HTML characters?

Yes it does. I thought that should be clear from my comment. But in case it's not, let me provide a detailed example. Imagine Alice is using Pidgin and Bob profanity.
Now Alice will type

```
Hey Bob

I really love the HTML <video> tag!
Also, check out this rad video: https://www.youtube.com/foo&bar
```

Pidgin will encode the message. Here is what Pidgin will send and subsequently profanity will receive:
```
Hey Bob<br /><br />I really love the HTML &lt;video&gt; tag!<br />Also, check out this rad video: https://www.youtube.com/foo&amp;bar
```

As you can see, Pidgin encodes the special characters typed in by Alice. This way it's easy to distinguish the HTML typed by Alice from the HTML added in by Pidgin.
Here is what, with my patch enabled, Bob will see:

```
Hey Bob

I really love the HTML <video> tag!
Also, check out this rad video: https://www.youtube.com/foo&bar
```

@asdil12: Haha. Very funny. Except, I'm not trying to *parse* HTML (nor XML). If you don't understand the difference, please don't try to be funny about it.

On an unrelated note: [XEP-0071](https://xmpp.org/extensions/xep-0071.html), which is the source of all HTML in XMPP and also of the all-otr-is-html-encoded debate (see below), standardises the use of xhtml 1.0 in XMPP. xhtml is not HTML5.

@boothj5  It might not be all that easy as just to say that the other clients are doing it wrong. To my knowledge, the reason why XMPP OTR messages are xhtml encoded is this: https://lists.cypherpunks.ca/pipermail/otr-dev/2008-May/000777.html Not this quote from Ian Goldberg in the mail:

> For example, suppose there's a Jabber message sent [...], where
> the body section contains an encryption of "to put something in bold,
> wrap around it" and the xhtml section contains an encryption of
> "to put something in bold, wrap <b></b> around it". Then an
> adversary replaces the OTR block in the xhtml section with the one from
> the body section. An end user with an xhtml-aware client will see "to
> put something in bold, wrap around it", and the attacker has
> successfully modified the message.

So you can't both have xhtml and body in an OTR message, at least not with different content. So the situation is an ugly mess from the beginning :(

**Comment by boothj5** [comment]
@NiklausHofer It's not so much that other clients are doing it wrong, more that they are making assumptions about the receiver that are not necessarily true.

In the post you refer to, there are two suggestions to fix this:  

* Its defined in the protocol (OTR), i.e. **all** OTR messages are HTML
* Its specified along with each message, i.e. one message includes a text/plain content type, another specifies text/xhtml

**Comment by nd2s** [comment]
@boothj5 I just uploaded some code [here](https://github.com/nd2s/profanity-plugin-sanitise). The problem is I couldn't get most of the Profanity parts working at all. I got some `print()` output from some stanza callback function, but nothing from `prof_init`, `prof_on_presence_stanza_receive` and `prof_on_contact_presence` (not sure which one of the latter ones I would need to use). I also tried using `prof.log_warning()` and throwing an exception - without any result.

**Comment by boothj5** [comment]
@nd2s cool, did you follow the instructions for building with plugin support etc here https://github.com/boothj5/profanity-plugins

I'm in the process of writing all the documentation before release.  I'll try to run your plugin later.

**Comment by boothj5** [comment]
@nd2s I've installed the plugin successfully.  I cloned your repository and then used the `/plugins` command to install it:

```
/plugins install ~/projects-git/profanity-plugin-sanitise/sanitise.py
```

The first attempt failed due my Python install not having the `lxml` library, from the Profanity logs:

```
08/08/2016 21:46:51: prof: INF: Failed to load plugin: sanitise.py
08/08/2016 21:46:51: stderr: ERR: Traceback (most recent call last):
08/08/2016 21:46:51: stderr: ERR:   File "/Users/boothj5/.local/share/profanity/plugins/sanitise.py", line 2, in <module>
08/08/2016 21:46:51: stderr: ERR:     from lxml import etree
08/08/2016 21:46:51: stderr: ERR: ImportError: No module named lxml
```

After installing the library using `pip`, the plugin loaded fine and calling `prof.cons_show("Hello world!")` for example works.

Attaching your profanity logs from when trying to load the plugin might help.

**Comment by NiklausHofer** [comment]
Well, whether you're going to merge or not, I still continued to write the patch. Because I actually need a fix for the stuff.

The current version now also includes an option to escape HTML special characters in outgoing OTR messages. This keeps for example the gajim OTR plugin from failing horribly on receiving URLs with ampersands.

I also made a dedicated repository just for the encode/decode functions. I guess that way it's easier for people to quickly checkout and review the actual code:

  https://gitlab.honet.ch/vimja/c_replace

**Comment by nd2s** [comment]
@boothj5 No idea what I did wrong, maybe I was half asleep because it works now. 

But Profanity really likes to segfault. It's probably my fault, but I think a Python plugin shouldn't be able to cause a segfault of the program. :)

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f837581a08f in PyObject_IsTrue () from /usr/lib/libpython3.5m.so.1.0
(gdb) bt
#0  0x00007f837581a08f in PyObject_IsTrue () from /usr/lib/libpython3.5m.so.1.0
#1  0x000000000048a5df in python_on_iq_stanza_receive_hook (plugin=0x18e93c0, 
    text=0x199caa0 "<iq id=\"_xmpp_session1\" to=\"foo@domain.com/resource\" type=\"result\"/>") at src/plugins/python_plugins.c:751
#2  0x00000000004848a7 in plugins_on_iq_stanza_receive (
    text=0x199caa0 "<iq id=\"_xmpp_session1\" to=\"foo@domain.com/resource\" type=\"result\"/>") at src/plugins/plugins.c:730
#3  0x00000000004290b1 in _iq_handler (conn=0x1987f20, stanza=0x199f850, userdata=0x1987e60)
    at src/xmpp/iq.c:141
#4  0x00007f837178166a in ?? () from /usr/lib/libmesode.so.0
#5  0x00007f837177e624 in ?? () from /usr/lib/libmesode.so.0
#6  0x00007f837178a07e in ?? () from /usr/lib/libmesode.so.0
#7  0x00007f836c4ca867 in ?? () from /usr/lib/libexpat.so.1
#8  0x00007f836c4cb83c in ?? () from /usr/lib/libexpat.so.1
#9  0x00007f836c4cfb6f in XML_ParseBuffer () from /usr/lib/libexpat.so.1
#10 0x00007f8371780e8d in xmpp_run_once () from /usr/lib/libmesode.so.0
#11 0x00000000004283ac in connection_check_events () at src/xmpp/connection.c:97
#12 0x00000000004279a2 in session_process_events () at src/xmpp/session.c:255
#13 0x00000000004210db in prof_run (log_level=0x4b4c20 "INFO", account_name=0x0)
    at src/profanity.c:123
#14 0x00000000004939f3 in main (argc=1, argv=0x7ffdbdbd7578) at src/main.c:148

```

**Comment by nd2s** [comment]
Segfaults happen when a function is called on an undefined object.

I almost have a first plugin version ready. But there is a problem: I need to sanitise based on a JID/resource pair but the `prof_pre_chat_message_display` hook only gives me JID without the resource as it seems.

**Comment by boothj5** [comment]
@nd2s I've added the `resource` argument to the chat message functions:

http://www.profanity.im/plugins/python/html/plugin.html#plugin.prof_pre_chat_message_display
http://www.profanity.im/plugins/python/html/plugin.html#plugin.prof_post_chat_message_display

Also added checks on return types for any functions that return something:

* If the value is undefined, a message should appear in the console (and the log) and Profanity should carry on as usual.
* The same should happen if return value is of the wrong type, for example if a hook that should return a string returns an integer
* There is no type checking on functions that should return a boolean since python can evaluate all types as a boolean

If you have a chance to try and break it again, I'd be interested to see how you get on.

**Comment by ari** [comment]
Could this plugin be put somewhere accessible to everything (like the official plugins repo) if it is now battle tested.

To be honest, I'd love a generic regex plugin to replace any content with anything else from a config file. For me, my use cases would be:

* replace ^<FONT> and </FONT>$ with empty string
* replace PROJ-1234 with http link to our bug tracker

But I'd settle for just the first thing!

**Comment by varac** [comment]
Ping, any progress on this ?

**Comment by jubalh** [comment]
OTR is not widely used anymore. And I can't get OTR in pidgin to work to test this.

**Comment by diego-treitos** [comment]
Sorry for the necrobump. 

If anybody ends up here. I am using this very small plugin that just does the trick, although of course it can be improved. At least it is a good start point.

```python
# -*- coding:utf-8 -*-
# vim: set ts=2 sw=2 sts=2 et:
import re
import prof
import html

#( regular expressions
re_font   = re.compile('</?FONT(>| [^>]+>)', re.IGNORECASE)
re_br     = re.compile('</?BR>', re.IGNORECASE)
re_styles = re.compile('</?(U|B|I)>', re.IGNORECASE)
re_link   = re.compile('</?a(>| [^>]+>)', re.IGNORECASE)
#)

def _htmlstrip(message):
  """ Cleans message
  """
  try:
    _message = message
    _message = re_styles.sub( '', _message )
    _message = re_font.sub( '', _message )
    _message = re_br.sub( '\n', _message )
    _message = re_link.sub( '', _message )

    _message = html.unescape( _message )
  except:
    return ("ERR@htmlstrip.py: " + message)
  finally:
    return (_message)

def prof_pre_chat_message_display(barejid, resource, message):
    return _htmlstrip(message)

def prof_pre_room_message_display(barejid, nick, message):
    return _htmlstrip(message)

def prof_pre_priv_message_display(barejid, nick, message):
    return _htmlstrip(message)
```

**Comment by jubalh** [comment]
@diego-treitos maybe worth adding to https://github.com/profanity-im/profanity-plugins ?

**Comment by diego-treitos** [comment]
@jubalh I'd love to. Should I add it to the `development` subfolder? I coded it today and barely tested it so I am not that confident about placing it as `stable`. On the other hand it is just a 34 lines of code...

Let me know where and I will submit a PR

**Comment by jubalh** [comment]
Great! You can put it in `stable`. Maybe also mention this issue in the commit message (just for reference).

**Comment by diego-treitos** [comment]
Added the PR https://github.com/profanity-im/profanity-plugins/pull/24
