### ISSUE TITLE
Integrate with Telepathy when possible

### ISSUE THREAD

**Issue by strugee** [profanity-im/profanity#379]
When Telepathy is available on the system, Profanity should attempt to get account information from the Telepathy service and route connections through it.

This would allow users to centralize their identities in the system. It would also allow conversations to be shared with other Telepathy clients, e.g. GNOME Shell.

I realize that this is possibly not something that the project is interested in doing, but the GNOME Shell integration is a deal-breaker for me. With the ability to share OTR-protected conversations across clients, I'd definitely consider adopting Profanity. The UI looks great, and it seems like you guys have a great project going on.

Thanks. For reference, here's the [Telepathy website](http://telepathy.freedesktop.org/wiki/), the [Telepathy D-Bus spec](http://telepathy.freedesktop.org/spec/), and the [FreeDesktop bug for adding OTR support](https://bugs.freedesktop.org/show_bug.cgi?id=OTR) to Telepathy.

**Comment by jubalh** [comment]
I have the impression Telepathy doesnt get a lot of attention on GNOME these days.
I would like to close this feature request since I think it would be of limited use anyways. Many people use profanity on systems without X. And I don't think we have the manpower to implement this and just benefitting a very small amount.
