### ISSUE TITLE
Text color on white background is unreadable

### ISSUE THREAD

**Issue by nud** [profanity-im/profanity#535]
The text color on white backgrounds is a light gray and doesn't match the command line default, i.e. apparently the profanity user interface doesn't adapt to the terminal theme like, say, irssi.

I didn't find any theme which overrides the text color in the distributed themes.

IMHO the default profanity theme should not define colors but should use the terminal-defined ones, as other CLI apps do. It would be an usability boost in the default setup for the many terminals which use a black on white color scheme by default (like gnome-terminal and konsole do)

The version I use is 0.4.6.

**Comment by clementino** [comment]
I'm interested in this issue too because I use a black on white terminal.
The version I use is from debian stable but I assume the problem is still there.
All but the "whiteness" and "hacker" themes are unreadable (on my netbook I don't see anything, the only way to read is by select and paste).

Using one of these two themes is good enough for me, but please make sure to always include some theme that is readable on a black on white terminal.
And of course it would be nice if the default theme was readable on both black on white and white on black terminals.
Thanks.

**Comment by josch** [comment]
I suffer from this problem too.

Maybe an easy solution which would at least make profanity text readable for us would be to explicitly set the background color just as you explicitly set the foreground (text) color. Then users of black-on-white terminals would properly see a white-on-black profanity window.

**Comment by nd2s** [comment]
I'm also looking for this. Setting the Profanity background color seems like a good (and quick) solution to me.

**Comment by nd2s** [comment]
I changed the value of `bkgnd` in file *themes/original* from `default` to `black`, ran `configure` and `make`, then `/theme load original` but nothing changed. What am I doing wrong?

**Comment by boothj5** [comment]
By default, themes are loaded from:

`$XDG_CONFIG_HOME/profanity/themes/`

Which will usually be:

`~/.config/profanity/themes/`

So if you make a change to a theme in the project source folder you'll have to run `make install` for the change to be installed to this folder.

You can also specify where you want Profanity to load themes from, when running `configure`, for example:

`./configure --with-themes=/home/me/projects/profanity/themes`

If you do this you'll need a clean build:

```
./configure --with-themes=/home/me/projects/profanity/themes
make clean
make
```

If you're just hacking to try things out, the easiest would be just to edit the themes in:

`~/.config/profanity/themes/`

Rather than the project source, and it will pick the changes up immediately without a rebuild etc.

Hope that helps.

**Comment by nd2s** [comment]
Ah thanks. Sorry I never ran `install` (have the latest stable version installed on the system) and thought they were just compiled into the binary (wouldn't have made much sense anyway).

Works perfectly now.

**Comment by japanoise** [comment]
Had the same issue, though I use a white-on-black terminal. I don't think the default theme should be explicitly setting the text color to white. Instead do like weechat and set it to _default_, i.e. `\e[39m`
