### ISSUE TITLE
inputrc settings not working for Control-0, Control-1 etc

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#831]
As reported in the chat room, with the following:

```
$if profanity
    "\C-Left": prof_win_prev                                                                                              
    "\C-Right": prof_win_next
    "\C-j": prof_win_pageup
    "\C-k": prof_win_pagedown
    "\C-h": prof_subwin_pageup
    "\C-l": prof_subwin_pagedown
    "\C-y": prof_win_clear
    "\C-0": prof_win_0
    "\C-1": prof_win_1
    "\C-2": prof_win_2
    "\C-3": prof_win_3
    "\C-4": prof_win_4
    "\C-5": prof_win_5
    "\C-6": prof_win_6
    "\C-7": prof_win_7
    "\C-8": prof_win_8
    "\C-9": prof_win_9
$endif
```

in ~/.inputrc and ~/.config/profanity/inputrc. Only effect is that the normal readline bindings won't work (Ctrl-Left for jumping back a word), but no result otherwise.

Using 0.5.0dev.master.8bcd142

**Comment by boothj5** [comment]
``"\C-Left"`` and ``"\C-Right"`` don't appear to be recognised by Readline.  The key sequence can be used instead.  To find the key sequence, in the terminal:

``cat -A``

And then do a control-left, the sequence should appear, e.g. in my terminal:

``^[[1;5D``

Then in inputrc:
```
"\e[1;5D": prof_win_prev
```

Note: the initial ``^[`` needs to be replaced with ``\e``.  Control-Left should then be able to be used to move to the previous window.

The ``"\C-1"``, ``"\C-2"`` etc seem to be a different problem.  Using ``cat -A`` to find the escape sequences for these key presses shows no escape sequences and in the case of ``"\C-4"`` actually sends a SIGQUIT to the running program.

I'll need to look into Readline a little deeper to see if there's a solution for the latter.

**Comment by jubalh** [comment]
@paulfertser you recently did something in this  part of the code. Did you see anything related or have an idea?

**Comment by paulfertser** [comment]
This is an interesting one, and it goes way below the GNU Readline level.
Basically, what you get pressing some of those ``Ctrl-<digit>`` combinations are ``ASCII control codes``, some have special meaning in the tty layer, some not; the translation sometimes happens even below any terminal (emulator) application code.
Specifically, if you're using Linux VT ("text console"), you get this mapping by default: https://elixir.bootlin.com/linux/latest/source/drivers/tty/vt/defkeymap.map#L17 . See how interesting control combinations with digits get there. If you're running X11 it switches keyboard to "raw" mode and does similar thing on its own: https://github.com/mirror/libX11/blob/master/src/KeyBind.c#L876 . You can see results of the translation with ``xev``.
The reason ``C-4`` sends ``SIGQUIT`` and ``C-8`` erases is because tty layer in cooked mode by default has ``quit = ^\; erase = ^?;`` , one can view and change it with ``stty``.
Now none of that answers how to get the intended results, but I have few ideas:
* if using X11 or Wayland, remap using ``xkb`` Ctrl key to Alt, and e.g. right Alt to Meta (Mod4) and use that (rather than Alt) for switching workspaces;
* if using text console, write a custom map so those combinations generate some easier to handle sequences rather than control codes;
* if using a keyboard running QMK firmware, do the remapping in there;
* try system-level key remapper https://github.com/rvaiya/keyd .

**Comment by jubalh** [comment]
I think we can leave this with @paulfertser explanation here. So that people know how to solve this bug.
If I understand it correctly we can't do anything about this in profanity.
