### ISSUE TITLE
Resize input field on longer written messages

### ISSUE THREAD

**Issue by kaffeekanne** [profanity-im/profanity#939]
This is more like a feature request. If you type a longer message the single input line scrolls. Of course it is possible to scroll back to see what has been written, but if the line wraps an the input fields grows, it would be easier to see what has been typed. If the input field grows like X lines oder XX% of vertical space, scrolling would be normal be normal behavior. The possibility to send line breaks via Ctrl-Return would chime in with this Feature.

I hope it is not to bold of a question to ask, but that is what woulld like like to see i an otherwise awesome XMPP client.

Regards

**Comment by jubalh** [comment]
It seems this issue is about two things:
* multiline messages, which already is tracked here https://github.com/boothj5/profanity/issues/182
* growing the input area when doing multiline messages

Personally I'm not sure the growing of the input area is a good idea. I think if the whole conversation view has to readjust every time to enter a new line it actually creates a more confusing/hectic impression because a lot of space in the screen changes.
All the curses programs I use (and can think of right now) don't grow the input line neither.

I would tend to close this issue about growing the input and track multi line messages in https://github.com/boothj5/profanity/issues/182

What's your opinion?

**Comment by kaffeekanne** [comment]
I agree about hectic UI. But i multiline messages are a thing in my daily use as i use citing and small code blocks with ` ``` ... ``` `. What do you think about making input space configurable for chat/muc windows (maybe xmlconsole)? That would be awesome. Allowing linebreaks and having a one line input field would be okayish too. I could adapt to that, somethinglike three lines would be my preferred setting.

**Comment by jubalh** [comment]
Will tackle this in https://github.com/profanity-im/profanity/issues/182
