### ISSUE TITLE
Feature: accept chat messages only from known contacts

### ISSUE THREAD

**Issue by d2-d2** [profanity-im/profanity#955]
Hello, first of all, profanity is really great. Thank you for your hard work.

I'd like to ask for a feature that will block spam on XMPP. Would it be possible to add such thing into profanity that would block direct chat messages from unknown users/contacts? In order to talk to me they need to be added/allowed to do so first.

If that feature already exists, please, could you point me to the right documentation (or maybe plugin?). Thanks in advance!

**Comment by jubalh** [comment]
Hi,

profanity can do this since 0.5.0. See `/help blocked`.

**Comment by jubalh** [comment]
Right. Will look into it.

**Comment by ge0rg** [comment]
This is actually a hard problem, and just blocking non-contacts is breaking the Jabber network in the long term. The problem is that most spammers also send you a subscription request, so subscription management is broken by them as well as messaging. You end up not knowing when somebody important tries to message you, or when they try to add you, and you can't contact or subscribe to other people either because they have the same filters set up.

The captcha / simple math challenge is an acceptable trade-off, but all this spam can be easily blocked on the server side (it follows very simple patterns). We are working on reporting such abused servers and blocking them:

* https://github.com/JabberSPAM/jabber-spam-fighting-manifesto
* https://github.com/JabberSPAM/blacklist

**Comment by d2-d2** [comment]
@ge0rg I understand this may not be an easy task, but spam is really annoying and must be somehow stopped. The links you provided are probably a good initiative but not enough. Reporting spam after the fact you've received 100+ messages is really not how I'd like to use profanity on daily basis. BTW, that blacklist.txt file contains literally two entries...

If messing with protocol is not an option then maybe captcha/custom challenge would do the trick? As far as I can tell Miranda and Pidgin are doing great job with stopping spam by showing captcha/challenge to user, not showing anything else to receipient if he/she do not solve a task. Maybe this is a correct way to stop this annoying spams?

**Comment by ge0rg** [comment]
@d2-d2 reporting individual JIDs won't work, yes. What we are doing is to report the abuse of In-Band-Registration to the server operators and ISPs. This takes some time, but in the end we remove the toxic (open relay) servers from the ecosystem. The blacklist only contains two servers (the project is young, and it takes time to report a domain and to escalate), but we've got over a dozen abandoned servers fixed / shut down in the process.

**Comment by jubalh** [comment]
@d2-d2 `/silence on`
